### ISSUE TITLE
Update bower repository to latest version

### ISSUE THREAD

**Issue by mrbatista** [srfrnk/ng-device-detector#19]
Please update to version 1.1.1

Thanks.

**Comment by srfrnk** [comment]
Hi @mrbatista,
Indeed the bower version is not updated to latest.
I couldn't see it explicitly stated but I guess bower now uses the npm version.
Since I never published to NPM it seems someone else registered the package on NPM registry so I can't make it update.
I've contacted NPM to try to solve it.
Only thing I can suggest as a workaround until they update the version is to get the latest version directly from github.
Sorry, hope it gets resolved soon.
Will update the issue when I have more news.

**Comment by srfrnk** [comment]
Version updated - release created.
