### ISSUE TITLE
iPad Air 2, ios 13.2 not recognized as tablet on safari

### ISSUE THREAD

**Issue by korengal** [srfrnk/ng-device-detector#87]
I just upgrade IOS version to  ios 13.2 and it is not recognized as tablet on safari.

Thanks.

**Comment by fadykstas** [comment]
On iOS 13 window.navigator.userAgent in Safari on iOS 13 is same as on MacOS. Something like this: 
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15
```
the reason is because "**Request Desktop Website**" parameter is now **enabled by default**, so instead of `os-ios` we get `os-mac` on iOS 13

Indeed, while option change in Settings may be a good solution for the user, any developer can't rely on that. It is as weird as to ask the user to not to use dark mode cause your app doesn't support it instead of opt-out of it using plist. 

Proposal is to add additional validation for `os-mac`:
```
const isIOS = navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1
```
real macs have no multi-touch support, this solution is ideal to detect iOS 13 devices which are the only multi-touch "MacIntel" devices in existence

**Comment by srfrnk** [comment]
This would be handled with https://github.com/srfrnk/ua-device-detector/issues/17

**Comment by andychangwalker** [comment]
@srfrnk Do any changes need to be made to ng-device-detector to get this working? We are using the latest release 5.1.4 and iPad Safari is reporting as a desktop device.

Thanks

**Comment by srfrnk** [comment]
Hi @andychangwalker `ng-device-detector` is configured to use `"ua-device-detector": "^1.1.1"` so if you update your dependencies it should pick up the latest version which is `1.1.8`. If a simple update fails do to that `rm -rf node_modules && npm i` should do the trick.
Let me know if this fails to help.

**Comment by andychangwalker** [comment]
Hi @srfrnk 

Sorry for the delay coming back. After checking ua-device-detector version it still wasn't working. I believe it was due to the MaxTouchPoints and Platform not being supplied by ng-device-detector so I modified the ng-device-detector code. I've created a pullrequest with my change for you to check.

Thanks

**Comment by srfrnk** [comment]
Thanks @andychangwalker,
Looks good.
Not sure how I forgot that.
Guess that's what happens when you try too do many things at the same time :)
